### ISSUE TITLE
Issue with OSM update in minutely data

### ISSUE THREAD

**Issue by HarelM** [IsraelHikingMap/OSMPbfWebAPI#1]
Seems like latest changes in OSM causes osmupdate to stop working.
This affect the code written here as it assumes osmupdate should work.
@zstadler there are probably two lines that need to change:
1. The code that runs this process: https://github.com/IsraelHikingMap/OSMPbfWebAPI/blob/c6e092813e26fbe5e0a17d5d6ced8ea5fe75557c/Controllers/OsmFileController.cs#L213
2. The docker file that installs osm-c-tools

**Comment by zstadler** [comment]
The replacement used for updating the vector tiles is `pyosmium-up-to-date`.

- It is installed using `apt-get install -y pyosmium`

Beyond syntactical differences, `pyosmium-up-to-date_` behaves differently than `osmupdate`:
1. It does not optimize the process by mixing daily, hourly, and minutely updates and consequencly it does not accept the `--day`, `--hour`, and `--minute` flags. Instead, the base url must be fully specified.  @HarelM, this requires changes in the service configuration mechanism

2. It is able to do in-place update of the pbf file, which can simplify the wrapper. For our use-case, the command line can be as simple as:

   ```

   pyosmium-up-to-date --server "http://download.openstreetmap.fr/replication/asia/israel_and_palestine/minute/" israel_and_palestine.osm.pbf

   ```

**Comment by HarelM** [comment]
While I don't mind changing the configuration etc, looking at the code and the new tool documentation I can't find a replacement to `osmconvert` for changing the timestamp of the daily pbf file, I'm also not sure if this is a historical bug fix or really needed...
Let me know if you think both tool are still needed or we can replace osm-c-tools with pyosmium completely.

**Comment by zstadler** [comment]
There is no change in initial download of the `pbf` file, which still needs `osmconvert`, `wget`, and our own processing of the state file.

**Comment by HarelM** [comment]
When I try to run the command inside my docker I get the following error message:
`Finished process pyosmium-up-to-date --server "http://download.openstreetmap.fr/replication/asia/israel_and_palestine/minute/" israel-and-palestine-latest.osm.pbf without sucsess 1`
It also spits the following errors before the process fails:
```
Starting process: pyosmium-up-to-date --server "http://download.openstreetmap.fr/replication/asia/israel_and_palestine/minute/" israel-and-palestine-latest.osm.pbf at /app/containers/IHM
2021-02-27 12:29:52,239 ERROR: HTTP Error 404: Not Found
2021-02-27 12:29:52,450 ERROR: HTTP Error 404: Not Found
2021-02-27 12:29:52,689 ERROR: HTTP Error 404: Not Found
2021-02-27 12:29:52,865 ERROR: HTTP Error 404: Not Found
2021-02-27 12:29:53,070 ERROR: HTTP Error 404: Not Found
2021-02-27 12:29:53,239 ERROR: HTTP Error 404: Not Found
Traceback (most recent call last):
  File "/usr/bin/pyosmium-up-to-date", line 228, in <module>
    ret = update_from_custom_server(url, seq, ts, options)
  File "/usr/bin/pyosmium-up-to-date", line 121, in update_from_custom_server
    extra_headers=extra_headers)
  File "/usr/lib/python2.7/dist-packages/osmium/replication/server.py", line 157, in apply_diffs_to_file
    diffs = self.collect_diffs(start_id, max_size)
  File "/usr/lib/python2.7/dist-packages/osmium/replication/server.py", line 93, in collect_diffs
    left_size -= rd.add_buffer(diffdata, self.diff_type)
RuntimeError: Unknown element in <way>: bbox
```

I have no clue what else I need to do in oder to make this work...

**Comment by HarelM** [comment]
Seems like this is irrelevant...
Closing...
